services:
  caddy:
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
    command: caddy run -c /config/Caddyfile
    cap_add:
      - NET_ADMIN
    environment:
      CADDY_ADMIN: unix//run/caddy/admin.sock
    env_file:
      - .env
    volumes:
      - /var/lib/uncloud/caddy:/data
      - /var/lib/uncloud/caddy:/config
      - /run/uncloud/caddy:/run/caddy
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost/.uncloud-verify"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    x-ports:
      - 80:80@host
      - 443:443@host
      - 443:443/udp@host
    x-caddy: Caddyfile
    deploy:
      mode: global
