services:
  adguard:
    image: adguard/adguardhome:latest
    volumes:
      - adguard-conf:/opt/adguardhome/conf
      - adguard-work:/opt/adguardhome/work
    x-caddy: |
      adguard.yusoofsh.cloud {
        reverse_proxy {{upstreams 80}}
      }
      dnsoh.yusoofsh.cloud {
        reverse_proxy {{upstreams 443}} {
          transport http {
            tls
            tls_insecure_skip_verify
            tls_server_name dnsoh.yusoofsh.cloud
          }
          import common_proxy
        }
      }
    x-ports:
      - 853:853/tcp@host
      - 853:853/udp@host

volumes:
  adguard-conf:
  adguard-work:
