services:
  adguard:
    image: adguard/adguardhome:beta
    cap_add:
      - NET_ADMIN
    volumes:
      - adguard-conf:/opt/adguardhome/conf
      - adguard-work:/opt/adguardhome/work
      - adguard-tls:/opt/adguardhome/tls
    x-caddy: |
      adguard.yusoofsh.cloud {
        redir / /home 302
        handle_path /home* {
          reverse_proxy {{upstreams 80}}
        }
        handle {
          reverse_proxy {{upstreams 80}}
        }
        handle /dns-query* {
          reverse_proxy {{upstreams 80}} {
            header_up Host {host}
          }
        }
      }
      *.adguard.yusoofsh.cloud {
        handle {
          reverse_proxy {{upstreams 80}}
        }
        handle /dns-query* {
          reverse_proxy {{upstreams 80}} {
            header_up Host {host}
          }
        }
      }
    x-ports:
      - 853:853/tcp@host
      - 853:853/udp@host
  lego:
    image: brahmadev/acme-lego-cron:latest
    env_file:
      - .env
    environment:
      - EMAIL_ADDRESS
      - PROVIDER=cloudflare
      - CLOUDFLARE_DNS_API_TOKEN
      - DOMAINS=adguard.yusoofsh.cloud;*.adguard.yusoofsh.cloud
    volumes:
      - adguard-tls:/letsencrypt

volumes:
  adguard-conf:
  adguard-work:
  adguard-tls:
